[v1]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-edit 0.12.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-make 0.37.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-make",
    "makers",
]
"wasm-bindgen-cli 0.2.87 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen",
    "wasm-bindgen-test-runner",
    "wasm2es6js",
]
"wasm-server-runner 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-server-runner"]
