#!/bin/sh
function colors() {
  for x in {0..8}; do
    for i in {0..37}; do
      for a in {40..47}; do
        echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m ";
      done;
      echo;
    done;
  done;
}


# custom shell agnostic color aliases
# copied from linux kernal log levels
export C_DEBUG="\e[0;34;40m"
export C_INFO="\e[0;32;40m"
export C_NOTICE="\e[0;30;42m"
export C_WARN="\e[0;36;40m"
export C_ERR="\e[0;35;40m"
export C_CRIT="\e[0;30;46m"
export C_ALERT="\e[0;31;40m"
export C_EMERG="\e[0;37;41m"
